name: Flask Advanced Blog CI/CD

on:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.9

      - name: Create Virtual Environment
        run: |
          python -m venv venv
          ls -la venv  # List the contents of the virtual environment directory
          ls -la venv/bin  # List the contents of the virtual environment's bin directory
          source venv/bin/activate
          which python  # Verify the path to the Python interpreter

      - name: Install dependencies
        run: |
          source venv/bin/activate
          python -m pip install -U pip
          python -m pip install -r requirements.txt

      - name: Print debugging information
        run: |
          echo "Python Version: $(python --version)"
          echo "Working Directory: $(pwd)"
          echo "Contents of Working Directory: $(ls -l)"
          echo "Contents of site-packages: $(ls -l venv/lib/python*/site-packages)"
          echo "List virtual environment directory: $(ls -la venv/bin)"
          echo "Print PATH environment variable: $PATH"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.9

      - name: Create Virtual Environment
        run: |
          python -m venv venv
          ls -la venv
          ls -la venv/bin
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          python -m pip install -U pip
          python -m pip install -r requirements.txt

      - name: Run any database migrations
        run: flask db upgrade

      - name: Run the tests
        run: python -m unittest discover -v -s .
