name: Flask Blog API CI/CD

on:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.9

      - name: Install dependencies
        run: |
          python3 -m venv venv
          venv/bin/pip install -U pip
          venv/bin/pip install -r requirements.txt

      - name: Print debugging information
        run: |
          venv/bin/python --version
          pwd
          ls -l
          ls -l venv/lib/python*/site-packages

  # Commented out test stage until tests are available
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     - name: Set Up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: 3.11.9

  #     - name: Install dependencies
  #       run: |
  #         python3 -m venv venv
  #         venv/bin/pip install -U pip
  #         venv/bin/pip install -r requirements.txt

  #     - name: Run any database migrations
  #       run: venv/bin/flask db upgrade

  #     - name: Run the tests
  #       run: venv/bin/python -m unittest discover -v -s .

