name: Flask E-Commerce CI/CD

on:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.9

      - name: Create Virtual Environment
        run: |
          python -m venv venv
          echo "VIRTUAL_ENV=$(pwd)/venv" >> $GITHUB_ENV
          echo "PATH=$(pwd)/venv/bin:$PATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          source $VIRTUAL_ENV/bin/activate
          python -m pip install -U pip
          python -m pip install -r requirements.txt

      - name: Print debugging information
        run: |
          source $VIRTUAL_ENV/bin/activate
          echo "Python Version: $(python --version)"
          echo "Working Directory: $(pwd)"
          echo "Contents of Working Directory: $(ls -l)"
          echo "Contents of site-packages: $(ls -l $(python -c 'import site; print(site.getsitepackages()[0])'))"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.9

      - name: Create Virtual Environment
        run: |
          python -m venv venv
          echo "VIRTUAL_ENV=$(pwd)/venv" >> $GITHUB_ENV
          echo "PATH=$(pwd)/venv/bin:$PATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          source $VIRTUAL_ENV/bin/activate
          python -m pip install -U pip
          python -m pip install -r requirements.txt

      - name: Run any database migrations
        run: |
          source $VIRTUAL_ENV/bin/activate
          flask db upgrade

      - name: Run the tests
        run: |
          source $VIRTUAL_ENV/bin/activate
          python -m unittest discover -v -s .

